schema_version = "1.0.0"

id = "hedgehog_engine_io_dev"
version = "0.1.118"
name = "Hedgehog Engine I/O DEV BUILD"
tagline = "Import/Exporter for Hedgehog Engine 3D related formats"
maintainer = "Justin113D, hedge-dev"
type = "add-on"

website = "https://github.com/hedge-dev/HedgehogEngineBlenderIO"
tags = ["Import-Export"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

wheels = [
  "./wheels/colorama-0.4.6-py2.py3-none-any.whl",
]

[permissions]
files = "Importing and exporting files"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.venv/",
  "/.vscode/",
  "/.git/",
  "*.bat",
  ".*",
  "*.blend1",
  "*.prod.*",
]